name       : sof-firmware
version    : '2.7'
release    : 12
source     :
    - https://github.com/thesofproject/sof-bin/releases/download/v2023.09/sof-bin-2023.09.tar.gz : 4bcc75c6642348e1a516db7ff9d050b6ea1b8672983542c6952562fa8c1c7b63
license    :
    - BSD-3-Clause
    - ISC
component  : kernel
summary    : Sound Open Firmware
description: |
    Sound Open Firmware
install    : |
    install -dm00755 $installdir/lib/firmware/intel
    cp -a sof "$installdir/lib/firmware/intel/sof"
    cp -a sof-ace-tplg "$installdir/lib/firmware/intel/sof-ace-tplg"
    cp -a sof-ipc4 "$installdir/lib/firmware/intel/sof-ipc4"
    cp -a sof-tplg "$installdir/lib/firmware/intel/sof-tplg"
